---
  - hosts: db
    become: true
    roles:
      - install-mongo

  - hosts: app
    become: true
    roles:
      - install-nodejs
      - deploy-app

  - hosts: nodes
    become: true
    roles:
      - install-nodejs
      - deploy-node
